### PR TITLE
Feature/fix recent issues

### PR DESCRIPTION
**Pull request by rulixxx**
Trying to do some simple fixes to the wrapper for the two issues that were pending. Also made the indentation consistent for all the script.

### CODE REVIEW

**Comment by keiranmraine** [comment]
Looks good, but won't merge until we have the docker internal CI running to test it fully.

**Comment by rulixxx** [comment]
Did a rebase to all new changes from dev into this branch

**Comment by keiranmraine** [comment]
FYI: @rulixxx the preferred method is to merge dev into your feature branch.  I know it adds an additional commit, but it is clear where in the chain the changes were added into the branch.

**Comment by keiranmraine** [comment]
@rulixxx can we close this (unmerged) until it is ready and then start the review process at that point.

**Pull request closed without merging**
